from models import MEIndicator

_counter = 0


def _id() -> str:
    global _counter
    _counter += 1
    return f"me-{_counter}"


ME_INDICATORS: list[MEIndicator] = [
    # ===== HEALTH =====
    MEIndicator(id=_id(), title="Under-5 mortality rate", definition="Probability of dying between birth and exact age 5, expressed per 1,000 live births", measurement_method="Administrative data / Health facility records", unit="Per 1,000 live births", frequency="annually", suggested_data_source="DHIS2 / National health information system", framework_source="SDG 3.2.1", sector="Health", category="Impact"),
    MEIndicator(id=_id(), title="Maternal mortality ratio", definition="Number of maternal deaths per 100,000 live births during a given time period", measurement_method="Health facility records / Verbal autopsy", unit="Per 100,000 live births", frequency="annually", suggested_data_source="DHIS2 / Facility registers", framework_source="SDG 3.1.1", sector="Health", category="Impact"),
    MEIndicator(id=_id(), title="Proportion of births attended by skilled health personnel", definition="Percentage of live births attended by skilled health personnel", measurement_method="Household survey / Administrative data", unit="%", frequency="annually", suggested_data_source="DHS / MICS surveys", framework_source="SDG 3.1.2", sector="Health", category="Outcome"),
    MEIndicator(id=_id(), title="Immunization coverage (DPT3)", definition="Percentage of children aged 12-23 months who received 3 doses of DPT vaccine", measurement_method="Administrative data / Survey", unit="%", frequency="quarterly", suggested_data_source="Health facility records / EPI reports", framework_source="SDG 3.b.1 / USAID HL.9.1-2", sector="Health", category="Output"),
    MEIndicator(id=_id(), title="HIV testing and counseling coverage", definition="Percentage of people who received HIV testing and counseling", measurement_method="Health facility records", unit="%", frequency="quarterly", suggested_data_source="Health facility registers / HMIS", framework_source="USAID HL.8.2-1", sector="Health", category="Output"),
    MEIndicator(id=_id(), title="Contraceptive prevalence rate", definition="Percentage of women of reproductive age using modern contraception", measurement_method="Household survey", unit="%", frequency="annually", suggested_data_source="DHS / PMA surveys", framework_source="SDG 3.7.1", sector="Health", category="Outcome"),
    MEIndicator(id=_id(), title="Number of health workers trained", definition="Number of health workers who completed in-service training programs", measurement_method="Training records / Administrative data", unit="Number", frequency="quarterly", suggested_data_source="Project training database", framework_source="USAID HL.9.3-1", sector="Health", category="Output"),
    MEIndicator(id=_id(), title="Incidence of malaria per 1,000 population", definition="Number of new malaria cases per 1,000 population at risk per year", measurement_method="Surveillance data / Health facility records", unit="Per 1,000", frequency="quarterly", suggested_data_source="DHIS2 / National malaria program", framework_source="SDG 3.3.3", sector="Health", category="Impact"),

    # ===== EDUCATION =====
    MEIndicator(id=_id(), title="Net enrollment rate (primary)", definition="Number of children of official primary school age enrolled in primary education as a percentage of total children of official primary school age", measurement_method="Administrative data / School records", unit="%", frequency="annually", suggested_data_source="EMIS / School census", framework_source="SDG 4.1.1 / World Bank", sector="Education", category="Outcome"),
    MEIndicator(id=_id(), title="Completion rate (primary)", definition="Percentage of children who complete the last grade of primary education", measurement_method="Administrative data", unit="%", frequency="annually", suggested_data_source="EMIS / UIS database", framework_source="SDG 4.1.2", sector="Education", category="Outcome"),
    MEIndicator(id=_id(), title="Proportion of children achieving minimum proficiency in reading", definition="Percentage of children at end of primary achieving minimum proficiency in reading", measurement_method="Learning assessment / Standardized test", unit="%", frequency="annually", suggested_data_source="National learning assessment", framework_source="SDG 4.1.1(a)", sector="Education", category="Impact"),
    MEIndicator(id=_id(), title="Pupil-teacher ratio", definition="Average number of pupils per teacher in primary education", measurement_method="Administrative data", unit="Ratio", frequency="annually", suggested_data_source="EMIS / School records", framework_source="World Bank / UIS", sector="Education", category="Output"),
    MEIndicator(id=_id(), title="Number of teachers trained", definition="Number of teachers who completed pre-service or in-service training", measurement_method="Training records", unit="Number", frequency="quarterly", suggested_data_source="Project records / MoE data", framework_source="USAID ES.1-3", sector="Education", category="Output"),
    MEIndicator(id=_id(), title="Gender parity index (primary enrollment)", definition="Ratio of female to male enrollment rate in primary education", measurement_method="Administrative data", unit="Index", frequency="annually", suggested_data_source="EMIS / UIS database", framework_source="SDG 4.5.1", sector="Education", category="Outcome"),
    MEIndicator(id=_id(), title="Out-of-school children rate", definition="Percentage of children of primary school age who are not enrolled in school", measurement_method="Household survey / Administrative data", unit="%", frequency="annually", suggested_data_source="UIS / MICS / DHS", framework_source="SDG 4.1", sector="Education", category="Impact"),
    MEIndicator(id=_id(), title="Number of classrooms built or rehabilitated", definition="Number of learning spaces constructed or renovated meeting minimum standards", measurement_method="Project monitoring / Site inspection", unit="Number", frequency="quarterly", suggested_data_source="Project records", framework_source="USAID ES.1-1", sector="Education", category="Output"),

    # ===== CLIMATE & ENVIRONMENT =====
    MEIndicator(id=_id(), title="CO₂ emissions per capita", definition="Total carbon dioxide emissions divided by mid-year population", measurement_method="National emissions inventory / Remote sensing", unit="tCO₂/capita", frequency="annually", suggested_data_source="National GHG inventory / UNFCCC", framework_source="SDG 13.2.2", sector="Climate & Environment", category="Impact"),
    MEIndicator(id=_id(), title="Proportion of land area covered by forest", definition="Forest area as a percentage of total land area", measurement_method="Remote sensing / Land survey", unit="%", frequency="annually", suggested_data_source="FAO FRA / National forest inventory", framework_source="SDG 15.1.1", sector="Climate & Environment", category="Impact"),
    MEIndicator(id=_id(), title="Hectares of land restored or reforested", definition="Total area of degraded land brought under restoration or reforestation", measurement_method="GIS mapping / Field verification", unit="Hectares", frequency="annually", suggested_data_source="Project GIS data / Field reports", framework_source="SDG 15.3.1 / Bonn Challenge", sector="Climate & Environment", category="Output"),
    MEIndicator(id=_id(), title="Number of people with improved climate resilience", definition="Number of individuals benefiting from climate adaptation measures", measurement_method="Survey / Project records", unit="Number", frequency="annually", suggested_data_source="Project beneficiary database", framework_source="USAID EG.11-6", sector="Climate & Environment", category="Outcome"),
    MEIndicator(id=_id(), title="Renewable energy capacity installed", definition="Total renewable energy generation capacity installed through the project", measurement_method="Technical records / Meter readings", unit="MW", frequency="annually", suggested_data_source="Project technical reports", framework_source="SDG 7.2.1", sector="Climate & Environment", category="Output"),
    MEIndicator(id=_id(), title="Greenhouse gas emissions reduced", definition="Estimated GHG emissions avoided or reduced through project interventions", measurement_method="Emissions modeling / Calculation methodology", unit="tCO₂e", frequency="annually", suggested_data_source="Project emissions calculations", framework_source="SDG 13.2.2 / GCF", sector="Climate & Environment", category="Impact"),

    # ===== AGRICULTURE & FOOD SECURITY =====
    MEIndicator(id=_id(), title="Prevalence of undernourishment", definition="Percentage of population whose habitual food consumption is insufficient to provide dietary energy needs", measurement_method="Household survey / Food security assessment", unit="%", frequency="annually", suggested_data_source="FAO / IPC / CFSVA", framework_source="SDG 2.1.1", sector="Agriculture & Food Security", category="Impact"),
    MEIndicator(id=_id(), title="Crop yield per hectare", definition="Average production of a specific crop per unit of harvested area", measurement_method="Crop cutting / Farmer survey", unit="kg/hectare", frequency="annually", suggested_data_source="Agricultural surveys / MoA data", framework_source="SDG 2.3.1 / FAO", sector="Agriculture & Food Security", category="Outcome"),
    MEIndicator(id=_id(), title="Number of farmers adopting improved technologies", definition="Number of farmers using improved seeds, techniques, or inputs promoted by the project", measurement_method="Survey / Extension records", unit="Number", frequency="quarterly", suggested_data_source="Project monitoring database", framework_source="USAID EG.3.2-24", sector="Agriculture & Food Security", category="Output"),
    MEIndicator(id=_id(), title="Food Consumption Score (FCS)", definition="Composite score measuring dietary diversity, food frequency, and nutritional importance", measurement_method="Household survey", unit="Score", frequency="quarterly", suggested_data_source="WFP food security surveys", framework_source="WFP / IPC", sector="Agriculture & Food Security", category="Outcome"),
    MEIndicator(id=_id(), title="Post-harvest loss rate", definition="Percentage of production lost after harvest due to handling, storage, or processing", measurement_method="Loss assessment survey / Weighing", unit="%", frequency="annually", suggested_data_source="FAO / Project assessments", framework_source="SDG 12.3.1 / FAO", sector="Agriculture & Food Security", category="Outcome"),
    MEIndicator(id=_id(), title="Hectares under improved management practices", definition="Total area applying sustainable land or water management practices", measurement_method="GIS / Extension records", unit="Hectares", frequency="annually", suggested_data_source="Project monitoring data", framework_source="USAID EG.3.2-25", sector="Agriculture & Food Security", category="Output"),
    MEIndicator(id=_id(), title="Number of value chain actors trained", definition="Number of individuals trained in agricultural value chain activities", measurement_method="Training records", unit="Number", frequency="quarterly", suggested_data_source="Project training records", framework_source="USAID EG.3.2-1", sector="Agriculture & Food Security", category="Output"),

    # ===== LIVELIHOODS & ECONOMIC DEVELOPMENT =====
    MEIndicator(id=_id(), title="Number of jobs created", definition="Number of new full-time equivalent positions created through project activities", measurement_method="Employer records / Survey", unit="Number", frequency="quarterly", suggested_data_source="Project records / Enterprise surveys", framework_source="SDG 8.5.2 / USAID EG.6-12", sector="Livelihoods & Economic Development", category="Outcome"),
    MEIndicator(id=_id(), title="Household income change", definition="Average change in household income among beneficiaries over the project period", measurement_method="Household survey / Income assessment", unit="% change or currency", frequency="baseline / midline / endline", suggested_data_source="Beneficiary survey data", framework_source="World Bank / USAID EG.3-2", sector="Livelihoods & Economic Development", category="Impact"),
    MEIndicator(id=_id(), title="Number of MSMEs supported", definition="Number of micro, small, and medium enterprises receiving project assistance", measurement_method="Administrative records", unit="Number", frequency="quarterly", suggested_data_source="Project database", framework_source="USAID EG.5-4", sector="Livelihoods & Economic Development", category="Output"),
    MEIndicator(id=_id(), title="Access to financial services", definition="Percentage of target population with access to formal financial services", measurement_method="Survey / Financial institution data", unit="%", frequency="annually", suggested_data_source="Financial inclusion surveys", framework_source="SDG 8.10.2", sector="Livelihoods & Economic Development", category="Outcome"),
    MEIndicator(id=_id(), title="Number of individuals completing vocational training", definition="Number of people who completed skills or vocational training programs", measurement_method="Training records", unit="Number", frequency="quarterly", suggested_data_source="Project training database", framework_source="SDG 4.3.1 / USAID EG.6-1", sector="Livelihoods & Economic Development", category="Output"),
    MEIndicator(id=_id(), title="Youth employment rate", definition="Percentage of youth (15-24) who are employed after project intervention", measurement_method="Follow-up survey / Administrative data", unit="%", frequency="annually", suggested_data_source="Post-training tracer studies", framework_source="SDG 8.6.1", sector="Livelihoods & Economic Development", category="Outcome"),

    # ===== GOVERNANCE & RULE OF LAW =====
    MEIndicator(id=_id(), title="Voter turnout in national elections", definition="Percentage of eligible population that voted in the most recent national election", measurement_method="Administrative data / Election commission", unit="%", frequency="baseline / midline / endline", suggested_data_source="National election commission", framework_source="SDG 16.7.1", sector="Governance & Rule of Law", category="Impact"),
    MEIndicator(id=_id(), title="Number of government officials trained", definition="Number of public sector officials who completed governance-related training", measurement_method="Training records", unit="Number", frequency="quarterly", suggested_data_source="Project training database", framework_source="USAID DR.4.2-2", sector="Governance & Rule of Law", category="Output"),
    MEIndicator(id=_id(), title="Citizens' trust in public institutions", definition="Percentage of population expressing trust in government institutions", measurement_method="Perception survey", unit="%", frequency="annually", suggested_data_source="Afrobarometer / Perception surveys", framework_source="SDG 16.6.2", sector="Governance & Rule of Law", category="Outcome"),
    MEIndicator(id=_id(), title="Number of laws or policies drafted/revised with project support", definition="Number of legal or policy instruments developed or reformed through project assistance", measurement_method="Policy tracking / Administrative records", unit="Number", frequency="annually", suggested_data_source="Project records / Government gazette", framework_source="USAID DR.1.2-1", sector="Governance & Rule of Law", category="Output"),
    MEIndicator(id=_id(), title="Corruption perception index score", definition="Score from Transparency International reflecting perceived public sector corruption", measurement_method="Expert survey / Perception index", unit="Score (0-100)", frequency="annually", suggested_data_source="Transparency International CPI", framework_source="SDG 16.5.1", sector="Governance & Rule of Law", category="Impact"),
    MEIndicator(id=_id(), title="Number of CSOs strengthened", definition="Number of civil society organizations receiving capacity building support", measurement_method="Administrative records / Assessment", unit="Number", frequency="quarterly", suggested_data_source="Project capacity assessments", framework_source="USAID DR.4.3-2", sector="Governance & Rule of Law", category="Output"),

    # ===== HUMAN RIGHTS =====
    MEIndicator(id=_id(), title="Number of human rights violations documented", definition="Number of reported and verified human rights violations over a period", measurement_method="Case documentation / Monitoring reports", unit="Number", frequency="quarterly", suggested_data_source="Human rights monitoring database", framework_source="OHCHR / USAID DR.3.1-1", sector="Human Rights", category="Output"),
    MEIndicator(id=_id(), title="Percentage of victims receiving legal assistance", definition="Proportion of identified victims who received legal aid or representation", measurement_method="Case management records", unit="%", frequency="quarterly", suggested_data_source="Legal aid provider records", framework_source="SDG 16.3.2 / USAID DR.3.2-1", sector="Human Rights", category="Outcome"),
    MEIndicator(id=_id(), title="Number of justice sector personnel trained", definition="Number of judges, prosecutors, or lawyers trained on human rights standards", measurement_method="Training records", unit="Number", frequency="quarterly", suggested_data_source="Project training database", framework_source="USAID DR.3.1-2", sector="Human Rights", category="Output"),
    MEIndicator(id=_id(), title="Public awareness of human rights", definition="Percentage of target population aware of their basic human rights", measurement_method="KAP survey", unit="%", frequency="baseline / midline / endline", suggested_data_source="Beneficiary perception survey", framework_source="OHCHR", sector="Human Rights", category="Outcome"),
    MEIndicator(id=_id(), title="Number of advocacy initiatives conducted", definition="Number of campaigns, dialogues, or public events on human rights issues", measurement_method="Activity records", unit="Number", frequency="quarterly", suggested_data_source="Project activity tracker", framework_source="OHCHR / USAID", sector="Human Rights", category="Output"),

    # ===== MIGRATION & DISPLACEMENT =====
    MEIndicator(id=_id(), title="Number of displaced persons assisted", definition="Number of internally displaced persons or refugees receiving project assistance", measurement_method="Beneficiary registration / Distribution records", unit="Number", frequency="monthly", suggested_data_source="UNHCR proGres / Project database", framework_source="SDG 10.7.2 / UNHCR", sector="Migration & Displacement", category="Output"),
    MEIndicator(id=_id(), title="Proportion of refugees with access to basic services", definition="Percentage of refugees with access to health, education, and shelter", measurement_method="Survey / Service delivery data", unit="%", frequency="quarterly", suggested_data_source="UNHCR / Service provider records", framework_source="GCR / SDG 1.4.1", sector="Migration & Displacement", category="Outcome"),
    MEIndicator(id=_id(), title="Number of durable solutions achieved", definition="Number of displaced persons achieving voluntary return, resettlement, or local integration", measurement_method="Case management records", unit="Number", frequency="annually", suggested_data_source="UNHCR / IOM data", framework_source="UNHCR / GCR", sector="Migration & Displacement", category="Impact"),
    MEIndicator(id=_id(), title="Percentage of displaced children enrolled in school", definition="Proportion of refugee/IDP children of school age enrolled in education", measurement_method="School enrollment data / Survey", unit="%", frequency="annually", suggested_data_source="UNHCR / UNICEF / EMIS", framework_source="SDG 4.1 / GCR", sector="Migration & Displacement", category="Outcome"),
    MEIndicator(id=_id(), title="Livelihood support provided to displaced populations", definition="Number of displaced persons receiving livelihood or economic support", measurement_method="Project records", unit="Number", frequency="quarterly", suggested_data_source="Project beneficiary database", framework_source="UNHCR / IOM", sector="Migration & Displacement", category="Output"),

    # ===== GENDER EQUALITY =====
    MEIndicator(id=_id(), title="Proportion of women in leadership positions", definition="Percentage of women in managerial or decision-making roles", measurement_method="Administrative records / Survey", unit="%", frequency="annually", suggested_data_source="Organizational records / National statistics", framework_source="SDG 5.5.2", sector="Gender Equality", category="Outcome"),
    MEIndicator(id=_id(), title="Gender-based violence prevalence", definition="Percentage of women aged 15+ who experienced physical or sexual violence in the past 12 months", measurement_method="Population survey", unit="%", frequency="baseline / midline / endline", suggested_data_source="DHS / VAW surveys", framework_source="SDG 5.2.1", sector="Gender Equality", category="Impact"),
    MEIndicator(id=_id(), title="Number of women accessing reproductive health services", definition="Number of women receiving family planning, antenatal, or postnatal care", measurement_method="Health facility records", unit="Number", frequency="quarterly", suggested_data_source="HMIS / Facility records", framework_source="SDG 3.7.1 / SDG 5.6.1", sector="Gender Equality", category="Output"),
    MEIndicator(id=_id(), title="Number of GBV survivors receiving support", definition="Number of GBV survivors who received psychosocial, legal, or medical support", measurement_method="Case management records", unit="Number", frequency="quarterly", suggested_data_source="GBV service provider records", framework_source="USAID GNDR-8", sector="Gender Equality", category="Output"),
    MEIndicator(id=_id(), title="Proportion of girls completing secondary education", definition="Percentage of girls who complete the last grade of secondary school", measurement_method="Administrative data", unit="%", frequency="annually", suggested_data_source="EMIS / UIS database", framework_source="SDG 4.1.2 / SDG 5.1", sector="Gender Equality", category="Outcome"),
    MEIndicator(id=_id(), title="Women's economic participation rate", definition="Percentage of working-age women engaged in economic activities", measurement_method="Labour force survey", unit="%", frequency="annually", suggested_data_source="ILO / National labour surveys", framework_source="SDG 8.5.2 / SDG 5.a.1", sector="Gender Equality", category="Impact"),

    # ===== WASH =====
    MEIndicator(id=_id(), title="Proportion of population using safely managed drinking water", definition="Percentage of population using a safely managed drinking water service", measurement_method="Household survey / Administrative data", unit="%", frequency="annually", suggested_data_source="JMP / MICS / DHS", framework_source="SDG 6.1.1", sector="Water, Sanitation & Hygiene (WASH)", category="Impact"),
    MEIndicator(id=_id(), title="Proportion of population using safely managed sanitation", definition="Percentage of population using safely managed sanitation services", measurement_method="Household survey", unit="%", frequency="annually", suggested_data_source="JMP / MICS / DHS", framework_source="SDG 6.2.1", sector="Water, Sanitation & Hygiene (WASH)", category="Impact"),
    MEIndicator(id=_id(), title="Number of water points constructed or rehabilitated", definition="Number of water supply facilities built or repaired to functioning standards", measurement_method="Project monitoring / Site inspection", unit="Number", frequency="quarterly", suggested_data_source="Project records / Water point mapping", framework_source="USAID HL.8.1-2", sector="Water, Sanitation & Hygiene (WASH)", category="Output"),
    MEIndicator(id=_id(), title="Number of people gaining access to improved water source", definition="Number of individuals with new access to an improved water supply", measurement_method="Beneficiary count / Water point user records", unit="Number", frequency="quarterly", suggested_data_source="Project beneficiary database", framework_source="SDG 6.1.1 / USAID", sector="Water, Sanitation & Hygiene (WASH)", category="Outcome"),
    MEIndicator(id=_id(), title="Handwashing with soap practice rate", definition="Percentage of population practicing handwashing with soap at critical times", measurement_method="Observation / KAP survey", unit="%", frequency="baseline / midline / endline", suggested_data_source="KAP survey data", framework_source="SDG 6.2 / UNICEF", sector="Water, Sanitation & Hygiene (WASH)", category="Outcome"),
    MEIndicator(id=_id(), title="Number of latrines constructed", definition="Number of household or institutional latrines built meeting minimum standards", measurement_method="Project monitoring / Site inspection", unit="Number", frequency="quarterly", suggested_data_source="Project construction records", framework_source="USAID HL.8.1-3", sector="Water, Sanitation & Hygiene (WASH)", category="Output"),

    # ===== PRIVATE SECTOR / ESG / SUPPLY CHAIN =====
    MEIndicator(id=_id(), title="Carbon footprint (Scope 1+2+3)", definition="Total greenhouse gas emissions across all scopes", measurement_method="Emissions inventory / Calculation", unit="tCO₂e", frequency="annually", suggested_data_source="GHG Protocol calculations", framework_source="GRI 305 / TCFD / SDG 13", sector="Private Sector / ESG / Supply Chain", category="Impact"),
    MEIndicator(id=_id(), title="Supplier sustainability compliance rate", definition="Percentage of suppliers meeting ESG requirements in audits", measurement_method="Supplier audit / Self-assessment", unit="%", frequency="annually", suggested_data_source="Supplier audit reports", framework_source="GRI 308 / GRI 414", sector="Private Sector / ESG / Supply Chain", category="Outcome"),
    MEIndicator(id=_id(), title="Gender pay gap ratio", definition="Ratio of average female to male remuneration", measurement_method="Payroll data analysis", unit="Ratio", frequency="annually", suggested_data_source="HR payroll system", framework_source="GRI 405-2 / SDG 8.5", sector="Private Sector / ESG / Supply Chain", category="Outcome"),
    MEIndicator(id=_id(), title="Lost time injury frequency rate (LTIFR)", definition="Number of lost-time injuries per million hours worked", measurement_method="Incident records / HR data", unit="Rate", frequency="quarterly", suggested_data_source="OHS incident database", framework_source="GRI 403-9 / SASB", sector="Private Sector / ESG / Supply Chain", category="Output"),
    MEIndicator(id=_id(), title="ESG disclosure score", definition="Completeness of ESG reporting against applicable framework", measurement_method="Framework gap analysis", unit="Score (%)", frequency="annually", suggested_data_source="ESG reporting platform", framework_source="GRI / SASB / TCFD", sector="Private Sector / ESG / Supply Chain", category="Outcome"),
    MEIndicator(id=_id(), title="Waste diversion rate", definition="Percentage of total waste diverted from landfill through recycling or composting", measurement_method="Waste tracking records", unit="%", frequency="quarterly", suggested_data_source="Waste management records", framework_source="GRI 306-4 / SDG 12.5", sector="Private Sector / ESG / Supply Chain", category="Output"),
    MEIndicator(id=_id(), title="Living wage compliance", definition="Percentage of workforce receiving at or above the living wage threshold", measurement_method="Payroll analysis / Benchmarking", unit="%", frequency="annually", suggested_data_source="HR records / Living wage benchmarks", framework_source="GRI 202 / SA8000", sector="Private Sector / ESG / Supply Chain", category="Impact"),
    MEIndicator(id=_id(), title="Community investment as % of revenue", definition="Percentage of revenue allocated to community development programs", measurement_method="Financial records", unit="%", frequency="annually", suggested_data_source="CSR / Finance reports", framework_source="GRI 413 / SDG 17", sector="Private Sector / ESG / Supply Chain", category="Output"),
]


def get_indicators_for_sector(sector: str) -> list[MEIndicator]:
    return [i for i in ME_INDICATORS if i.sector == sector]
